name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # v2 から Node 24に対応した最新の v6 に変更
      - uses: actions/checkout@v6

      # v1 から 最新の v2 に変更（古いバージョン固定の「with」は不要になったため削除）
      - uses: denoland/setup-deno@v2

      - name: Check fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run type check
        run: deno cache *.ts
